### ISSUE TITLE
https://www.home-assistant.io/blog/2021/01/14/security-bulletin/ - Now error in this custom intgration

### ISSUE THREAD

**Issue by sanderlv** [barban-dev/homeassistant-midea-dehumidifier#10]
Today home assistant has issued a security warning regarding custom components. After updating home assistant I immediately get this custom integration to produce an error.
```

Logger: homeassistant.setup
Source: custom_components/midea_dehumidifier/__init__.py:66
First occurred: 8:47:00 AM (1 occurrences)
Last logged: 8:47:00 AM
Error during setup of component midea_dehumidifier

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/midea_dehumidifier/__init__.py", line 66, in async_setup
    res = await hass.async_add_executor_job(client.login)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/midea_inventor_lib/midea_client.py", line 69, in login
    response = self.__api_request("/v1/user/login/id/get", {"loginAccount": self.email})
  File "/usr/local/lib/python3.8/site-packages/midea_inventor_lib/midea_client.py", line 585, in __api_request
    response = self.__send_api_request(path, args)
  File "/usr/local/lib/python3.8/site-packages/midea_inventor_lib/midea_client.py", line 596, in __send_api_request
    data = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Is this one of the integration that is compromising?

**Comment by HVPereira** [comment]
Same issue here :(

**Comment by barban-dev** [comment]
Sorry, I cannot reproduce the reported issue: the custom integration is running fine on ** Home Assistant core-2021.1.4**

**Comment by merti29** [comment]
same problem here but it does not look like a integration problem. i have a comfee dehumidifier running and it worked well under 0.96. The Problem is, that the online Service itself is not reachable. the nethome plus app reports an error reaching my account. Havent changed anything else, so it seems to be a cloud provider problem at this moment

**Comment by merti29** [comment]
cloud server is fixed, plugin working now fine again ! Great Work

**Comment by barban-dev** [comment]
Thank you for reporting back that everything is working fine.
