### ISSUE TITLE
Integration could not be set up after update to HA 5.12

### ISSUE THREAD

**Issue by rul3zz** [barban-dev/homeassistant-midea-dehumidifier#15]
Hello, the integration could not be set up after update to HA 5.12

Logger: homeassistant.bootstrap
Source: bootstrap.py:392
Waiting on integrations to complete setup: midea_dehumidifier

**Comment by HVPereira** [comment]
The same happened to me

**Comment by drthanwho** [comment]
Quite unlikely that an OS update would cause an issue to an integration though

_Waiting on integration to complete setup_ isn't an error itself, but just info saying it's not ready yet

**Comment by HVPereira** [comment]
Did you try it? I am using Hass.io and it happened the exact same error to me.

**Comment by drthanwho** [comment]
You definitely aren't using Hassio as it no longer exists ;)

My production is also having issues as of the last hour. However I'm on 5.2 and not 5.12

Also attempted to set it up on my dev instance form scratch and experiencing exact same issue. Unlikely it is the OS though (on 5.11 there). 
I have also downloaded the app itself and that is also failing to log me in (thought I might have exceeded some defined number of attempts but I cannot even create a new account). Perhaps an issue on their side instead

**Comment by ronmichel** [comment]
Login via the official (nethome) app is also not working for me right now. Seems to be a server problem.

**Comment by HVPereira** [comment]
Sorry. Yes you are right I've tried to login via app and it doesn't work for me either.

Anyhow I leave my log below:

`2021-02-26 16:16:43 ERROR (MainThread) [homeassistant.setup] Error during setup of component midea_dehumidifier
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x6f67cc58>: Failed to establish a new connection: [Errno 110] Operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mapp.appsmb.com', port=443): Max retries exceeded with url: /v1/user/login/id/get (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x6f67cc58>: Failed to establish a new connection: [Errno 110] Operation timed out'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/midea_dehumidifier/__init__.py", line 66, in async_setup
    res = await hass.async_add_executor_job(client.login)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/midea_inventor_lib/midea_client.py", line 69, in login
    response = self.__api_request("/v1/user/login/id/get", {"loginAccount": self.email})
  File "/usr/local/lib/python3.8/site-packages/midea_inventor_lib/midea_client.py", line 585, in __api_request
    response = self.__send_api_request(path, args)
  File "/usr/local/lib/python3.8/site-packages/midea_inventor_lib/midea_client.py", line 592, in __send_api_request
    response = requests.post(uri, data=args)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mapp.appsmb.com', port=443): Max retries exceeded with url: /v1/user/login/id/get (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x6f67cc58>: Failed to establish a new connection: [Errno 110] Operation timed out'))
/usr/local/lib/python3.8/site-packages/construct/core.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp`

**Comment by sanderlv** [comment]
Same here for around 2 days now. 
```

Logger: homeassistant.setup
Source: custom_components/midea_dehumidifier/__init__.py:66
First occurred: 2:43:26 AM (1 occurrences)
Last logged: 2:43:26 AM

Error during setup of component midea_dehumidifier
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8d0e9e79d0>: Failed to establish a new connection: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mapp.appsmb.com', port=443): Max retries exceeded with url: /v1/user/login/id/get (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8d0e9e79d0>: Failed to establish a new connection: [Errno 110] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/midea_dehumidifier/__init__.py", line 66, in async_setup
    res = await hass.async_add_executor_job(client.login)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/midea_inventor_lib/midea_client.py", line 69, in login
    response = self.__api_request("/v1/user/login/id/get", {"loginAccount": self.email})
  File "/usr/local/lib/python3.8/site-packages/midea_inventor_lib/midea_client.py", line 585, in __api_request
    response = self.__send_api_request(path, args)
  File "/usr/local/lib/python3.8/site-packages/midea_inventor_lib/midea_client.py", line 592, in __send_api_request
    response = requests.post(uri, data=args)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mapp.appsmb.com', port=443): Max retries exceeded with url: /v1/user/login/id/get (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8d0e9e79d0>: Failed to establish a new connection: [Errno 110] Operation timed out'))

```

**Comment by drthanwho** [comment]
Yeah this is exactly what I'm seeing on mine too

**Comment by ronmichel** [comment]
Working again.

**Comment by rul3zz** [comment]
> Working again.

mine is still KO, the entity is unavailable. The Midea App work

**Comment by rul3zz** [comment]
> Working again.

mine too
