### ISSUE TITLE
HA 2021.3.3 logs  'NoneType' is not iterable ERROR

### ISSUE THREAD

**Issue by stalakerob** [barban-dev/homeassistant-midea-dehumidifier#19]
The following error is logged when using Home Assistant 2021.3.3 and the most recent version of midea dehumidifier custom component:

`home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 277, in async_update_ha_state
home-assistant   |     await self.async_device_update()
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_device_update
home-assistant   |     raise exc
home-assistant   |   File "/config/custom_components/midea_dehumidifier/humidifier.py", line 402, in async_update
home-assistant   |     res = await self.hass.async_add_executor_job(self._client.get_device_status, self._device['id'])
home-assistant   |   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
home-assistant   |     result = self.fn(*self.args, **self.kwargs)
home-assistant   |   File "/usr/local/lib/python3.8/site-packages/midea_inventor_lib/midea_client.py", line 203, in get_device_status
home-assistant   |     decodedReplyStr = self.appliance_transparent_send(deviceId, dataStr)
home-assistant   |   File "/usr/local/lib/python3.8/site-packages/midea_inventor_lib/midea_client.py", line 553, in appliance_transparent_send
home-assistant   |     if not "reply" in result:
home-assistant   | TypeError: argument of type 'NoneType' is not iterable
`

**Comment by shudack** [comment]
I have the same output with HA 2021.3.4

**Comment by robertolamm** [comment]
Also here.
