### ISSUE TITLE
Integration stoppped working

### ISSUE THREAD

**Issue by polemopouli** [barban-dev/homeassistant-midea-dehumidifier#20]
Hello!

The integration stopped working some days now. This is the HASS error log.

```
2021-03-17 23:31:53 ERROR (SyncWorker_6) [root] MideaClient::send_api_request: errorCode=3176, errorMessage="The asyn reply does not exist "
2021-03-17 23:31:53 ERROR (MainThread) [homeassistant.helpers.entity] Update for humidifier.midea_dehumidifier_XXXXXXXXXXXXXX fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 277, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_device_update
raise exc
File "/config/custom_components/midea_dehumidifier/humidifier.py", line 402, in async_update
res = await self.hass.async_add_executor_job(self._client.get_device_status, self._device['id'])
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.8/site-packages/midea_inventor_lib/midea_client.py", line 203, in get_device_status
decodedReplyStr = self.appliance_transparent_send(deviceId, dataStr)
File "/usr/local/lib/python3.8/site-packages/midea_inventor_lib/midea_client.py", line 553, in appliance_transparent_send
if not "reply" in result:
TypeError: argument of type 'NoneType' is not iterable
```

I believe they changed something about their API because the same time this happened, an update of the "INVmate II" on android was released.

**Comment by polemopouli** [comment]
Problem resolved without any changes...
