### ISSUE TITLE
Integration blocked

### ISSUE THREAD

**Issue by fralitri** [barban-dev/homeassistant-midea-dehumidifier#33]
After update core 2021.7.2 the integration stop to work! Any suggestions?

**Comment by mcfly2283-ai** [comment]
Spent my Log: 

benutzerdefinierte

Logger: homeassistant.helpers.entity
Source: custom_components/midea_dehumidifier/humidifier.py:401
Integration: EVA II PRO WiFi Midea Inventor Dehumidifier custom integration (documentation, issues) 
First occurred: 13. Juli 2021, 23:07:11 (494 occurrences) 
Last logged: 7:13:13

Update for humidifier.midea_dehumidifier_18691697902438 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 401, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 609, in async_device_update
    raise exc
  File "/config/custom_components/midea_dehumidifier/humidifier.py", line 401, in async_update
    res = await self.hass.async_add_executor_job(self._client.get_device_status, self._device['id'])
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/midea_inventor_lib/midea_client.py", line 203, in get_device_status
    decodedReplyStr = self.appliance_transparent_send(deviceId, dataStr)
  File "/usr/local/lib/python3.9/site-packages/midea_inventor_lib/midea_client.py", line 522, in appliance_transparent_send
    response = self.__api_request("/v1/appliance/transparent/send",
  File "/usr/local/lib/python3.9/site-packages/midea_inventor_lib/midea_client.py", line 585, in __api_request
    response = self.__send_api_request(path, args)
  File "/usr/local/lib/python3.9/site-packages/midea_inventor_lib/midea_client.py", line 596, in __send_api_request
    data = response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mcfly2283-ai** [comment]
So, after Rollback to 2021.7.1 - same Problem as above.

Humidity-Sensor and API-Connection went down yesterday (GMT+1)
![image](https://user-images.githubusercontent.com/77355612/125570860-dad5f508-886b-4b59-9ac0-55fe83a6dfe1.png)

**Comment by tobiasbayer** [comment]
Same problem here without any upgrades on home assistant. Integration just stopped working with the same error message.

**Comment by langerma** [comment]
yeah same problem here without update.

**Comment by saltabas** [comment]
Same issue after 21.7.2 upgrade, but I can see troubles in android app side, maybe it's just a coincidence. It refuse connection

**Comment by tobiasbayer** [comment]
Android app works for me

**Comment by mcfly2283-ai** [comment]
> Same issue after 21.7.2 upgrade, but I can see troubles in android app side, maybe it's just a coincidence. It refuse connection

Yeah, maybe there was also a Problem with the iOS-App yesterday. But after a short period it was fine for me.

**Comment by braini75** [comment]
Same for me!
Last successful communication was yesterday, 2021-07-13 at 2:30 pm! Then the login at android app was not possible for few hours. Android App is working now, but no connection with HA.

**Comment by Andy66622** [comment]
Same with the iOS App, since yesterday there is connection only in the local network and no connection with HA. Maybe the Cloud service is down.

**Comment by mcfly2283-ai** [comment]
> Same with the iOS App, since yesterday there is connection only in the local network and no connection with HA. Maybe the Cloud service is down.

Oh... Yeah. I dont have tested this before! :D 

So obviously its an Server-Problem as you said…

**Comment by fotis3d** [comment]
Same here. After updating HA it was dropped. I rolled back cause of another issue I found but problem still persists while the Android app works.

**Comment by tobiasbayer** [comment]
Seems to be back to normal for me.

**Comment by saltabas** [comment]
It's working again

**Comment by fotis3d** [comment]
Yeap it's back. :)

**Comment by fralitri** [comment]
Now work ! 🤷‍♂️
