### ISSUE TITLE
Error during setup of component Midea dehumidifier

### ISSUE THREAD

**Issue by phillipredshirt** [barban-dev/homeassistant-midea-dehumidifier#35]
2021-09-02 16:33:47 ERROR (MainThread) [homeassistant.setup] Error during setup of component midea_dehumidifier
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 249, in _async_setup_component
result = await task
File "/config/custom_components/midea_dehumidifier/__init__.py", line 82, in async_setup
if a["onlineStatus"] == "1":
UnboundLocalError: local variable 'a' referenced before assignment

**Comment by ankostis** [comment]
I guess there is some mistake in the identation, all the lines below belong to the for-loop.
I will draft a PR.

**Comment by ankostis** [comment]
I guess the identation-error was not caught because the code kicks only when the appliance is offline.
