### ISSUE TITLE
Dehumidifier state no longer updates

### ISSUE THREAD

**Issue by drthanwho** [barban-dev/homeassistant-midea-dehumidifier#36]
I was able to turn the dehumidifier on from HA but since I cannot turn it off and even if turning it off from the app the state doesn't update in HA anymore.  

```
2021-10-24 13:36:19 ERROR (SyncWorker_4) [root] MideaClient::send_api_request: errorCode=3176, errorMessage="The asyn reply does not exist "
2021-10-24 13:36:19 ERROR (MainThread) [homeassistant.helpers.entity] Update for humidifier.eva_ii fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 469, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 659, in async_device_update
    raise exc
  File "/config/custom_components/midea_dehumidifier/humidifier.py", line 401, in async_update
    res = await self.hass.async_add_executor_job(self._client.get_device_status, self._device['id'])
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/midea_inventor_lib/midea_client.py", line 203, in get_device_status
    decodedReplyStr = self.appliance_transparent_send(deviceId, dataStr)
  File "/usr/local/lib/python3.9/site-packages/midea_inventor_lib/midea_client.py", line 553, in appliance_transparent_send
    if not "reply" in result:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by nerdosity** [comment]
same here

**Comment by drthanwho** [comment]
Seems more of an issue on the cloud's side. Now everything is working OK. Logging never goes away so have just removed those logs so they don't show up

**Comment by barban-dev** [comment]
> Seems more of an issue on the cloud's side. Now everything is working OK. Logging never goes away so have just removed those logs so they don't show up
I can confir that. BR
