### ISSUE TITLE
Errors "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state await self.async_device_update()

### ISSUE THREAD

**Issue by robertolamm** [barban-dev/homeassistant-midea-dehumidifier#49]
Hello,
I have a lot of these errors in the log.

As mentioned in the issue #48, the status are not correct.... In addition the state is never in "unavailable", also when I remove the device from the electric socket.

Is only my problem ?

thx

Logger: homeassistant.helpers.entity
Source: custom_components/midea_dehumidifier/humidifier.py:401
Integration: EVA II PRO WiFi Midea Inventor Dehumidifier custom integration (documentation, issues)
First occurred: 15:44:34 (47 occurrences)
Last logged: 16:02:34

Update for humidifier.midea_dehumidifier_31885837251661 fails
Update for humidifier.midea_dehumidifier_31885837250678 fails
Update for humidifier.midea_dehumidifier_31885837243008 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/config/custom_components/midea_dehumidifier/humidifier.py", line 401, in async_update
    res = await self.hass.async_add_executor_job(self._client.get_device_status, self._device['id'])
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/midea_inventor_lib/midea_client.py", line 203, in get_device_status
    decodedReplyStr = self.appliance_transparent_send(deviceId, dataStr)
  File "/usr/local/lib/python3.9/site-packages/midea_inventor_lib/midea_client.py", line 553, in appliance_transparent_send
    if not "reply" in result:
TypeError: argument of type 'NoneType' is not iterable

**Comment by fotis3d** [comment]
I also get A LOT of errors on this intergration lately.

**Comment by varac** [comment]
Same for me, whenever I power off the device I get this `TypeError: argument of type 'NoneType' is not iterable` error.
