### ISSUE TITLE
Dehumidifier_FD40 not recognized

### ISSUE THREAD

**Issue by domerich** [barban-dev/homeassistant-midea-dehumidifier#68]
Hi guys, many years back I bought a Midea Humidifier, it calls itself dehumidifier_FD40 in the nethome plus App. Will this device work with this integration? I tried to configure the integration but nothing shows up. In the App settings it says 1FAFD4000000. It looks like this [one ](https://www.amazon.de/gp/product/B07MSL8YN7/ref=as_li_tl?ie=UTF8&tag=barban0704-21&camp=1638&creative=6742&linkCode=as2&creativeASIN=B07MSL8YN7&linkId=2fd83383be6c3a602d102508a9c2d627&th=1)

`Logger: homeassistant.loader
Source: loader.py:842
First occurred: 12:09:26 PM (2 occurrences)
Last logged: 12:09:26 PM

Unexpected exception importing platform custom_components.midea_dehumidifier.sensor
Unexpected exception importing platform custom_components.midea_dehumidifier.humidifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/midea_dehumidifier/sensor.py", line 54
    	self._device_class = SensorDeviceClass.HUMIDITY
    ^
TabError: inconsistent use of tabs and spaces in indentation`

**Comment by domerich** [comment]
this fixed it, grazie

https://github.com/barban-dev/homeassistant-midea-dehumidifier/issues/64#issuecomment-1878701372
